version: '3.8'
services:
  postgres:
    container_name: sale-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sale
    ports:
      - "5432:5432"
    volumes:
      - sale-data-volume:/applis/docker-compose/data

volumes:
  sale-data-volume:
    external: false
